Adds some more uses for ISVS
OWASP/IoT-Security-Verification-Standard-ISVS pull request #38
Opened 2021-01-13 21:06 UTC by tkisason

1. Adds info about how to use ISVS in design requirements
2. Adds info about how to use ISVS in procurement
3. Adds info about how to use ISVS in IoT Security Training
4. Adds info about how to use ISVS in agile security practices.

2021-01-22 02:08 UTC, scriptingxss requested changes
Really appreciate the time you've invested to help apply more color to ISVS' uses.

2021-01-23 20:57 UTC, tkisason commented on en/Using_ISVS.md
> +- The requirements listed in the ISVS can be used during the requirement elicitation phase of the project. For example, when defining security requirements in the beginning of a products secure devel
Accepted

2021-01-23 20:57 UTC, tkisason commented on en/Using_ISVS.md
> +- When developing internal or external IoT security trainings, ISVS can be used to guide trainings so they contain best practices on what should be done in specific cases instead of demoing or showin
Accepted

2021-01-23 20:59 UTC, tkisason commented on en/Using_ISVS.md
> +- The ISVS can be used as a framework to guide the agile development process in order to have a more secure product. Since most new IoT devices hardware will first be developed from a prototype syste
Accepted

2021-01-23 21:00 UTC, tkisason commented
Updated according to change request. Please see if it's better now.

2021-02-02 15:01 UTC, scriptingxss approved these changes

2021-02-02 15:01 UTC, merged